apiVersion: v1
kind: Service
metadata:
  name: support-chat-backend
  namespace: support-chat-stage
  labels:
    app: support-chat-backend
    environment: stage
spec:
  type: ClusterIP
  selector:
    app: support-chat-backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
